// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class virt_lab_4 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen;
    whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void test() {
    System.out.println("Розпочинаємо тест");
    driver.get("https://ldubgd.edu.ua//");
    driver.manage().window().setSize(new Dimension(600, 800));
    System.out.println("Записуємо Handle основного вікна та виводимо його");
    vars.put("ND", driver.getWindowHandle());
    System.out.println(vars.get("ND").toString());
    System.out.println("Переходимо на вкладку Курсанту/студенту");
    driver.findElement(By.linkText("Курсанту/студенту")).click();
    vars.put("window_handles", driver.getWindowHandles());
    System.out.println("Відкриваємо Віртуальний Університет");
    driver.findElement(By.linkText("Віртуальний університет")).click();
    vars.put("virt_9", waitForWindow(2000));
    driver.switchTo().window(vars.get("virt_9").toString());
    System.out.println("Шукаємо та натискаємо на лінку Вхід");
    {
      List<WebElement> elements = driver.findElements(By.linkText("Вхід"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Вхід")).click();
    System.out.println("Створюємо змінну test1 та записуємо у неї значення");
    vars.put("test1", "seleniumtest_store");
    System.out.println(vars.get("test1").toString());
    System.out.println("Створюємо дві змінну test2 та записуємо у неї значення");
    vars.put("test2", "seleniumtest");
    System.out.println(vars.get("test2").toString());
    System.out.println("Використовуємо знаяення змінних test1 та test2 у якості Логіна та Паролю");
    driver.findElement(By.id("username")).sendKeys(vars.get("test1").toString());
    driver.findElement(By.id("password")).sendKeys(vars.get("test2").toString());
    {
      String value = driver.findElement(By.id("username")).getAttribute("value");
      assertThat(value, is(vars.get("test1").toString()));
      System.out.println("Елемент Логін заповнено вірно");
    }
    {
      String value = driver.findElement(By.id("password")).getAttribute("value");
      assertThat(value, is(vars.get("test2").toString()));
      System.out.println("Елемент Пароль заповнено вірно");
    }
    driver.switchTo().window(vars.get("ND").toString());
    {
      WebElement element = driver.findElement(By.xpath("//a[2]/img"));
      String attribute = element.getAttribute("src");
      vars.put("attrib_1", attribute);
      }
    System.out.println(vars.get("attrib_1").toString());
    vars.put("text_1", driver.findElement(By.xpath("//*[@id=\"block-block-7--2\"]/div/h2")).getText());
    System.out.println(vars.get("text_1").toString());
    vars.put("value_1", driver.findElement(By.id("edit-submit")).getAttribute("value"));
    System.out.println(vars.get("value_1").toString());
    driver.switchTo().window(vars.get("virt_9").toString());
    driver.close();
    driver.switchTo().window(vars.get("ND").toString());
    driver.close();
  }
}
